services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9002:9001"
      - "9003:9000"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    restart: always